/**
 * GET /api/stripe/fulfill?session_id=cs_...
 * Returns a one-time download URL for a paid Stripe Checkout Session.
 *
 * This is intended for redirect-based fulfillment (success page on your site).
 * It reuses the token generated by the webhook when available, otherwise it
 * can generate a new watermarked PDF and token after verifying payment.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const express = require('express');
const Stripe = require('stripe');
const stripeLib = require('../lib/stripe');
const watermark = require('../lib/watermark');
const onetime = require('../lib/onetime');
const tokenStore = require('../store/tokens');
const stripeSessions = require('../store/stripeSessions');

const router = express.Router();
const TEMP_DIR = path.join(__dirname, '..', 'temp');

function ensureTempDir() {
  if (!fs.existsSync(TEMP_DIR)) {
    fs.mkdirSync(TEMP_DIR, { recursive: true });
  }
}

function getBaseUrl() {
  return (
    (process.env.BASE_URL || '').replace(/\/$/, '') ||
    `http://localhost:${process.env.PORT || 4000}`
  );
}

function getResolvedMasterPdf() {
  const masterPath = process.env.MASTER_PDF_PATH;
  if (!masterPath) {
    throw new Error('MASTER_PDF_PATH not configured');
  }
  const resolved = path.isAbsolute(masterPath)
    ? masterPath
    : path.join(__dirname, '..', masterPath);
  if (!fs.existsSync(resolved)) {
    throw new Error('Master PDF not found');
  }
  return resolved;
}

function isPaidSession(session) {
  // Stripe varies by API version; these are the common signals.
  if (!session) return false;
  if (session.payment_status === 'paid') return true;
  if (session.status === 'complete') return true;
  return false;
}

router.get('/fulfill', async (req, res) => {
  try {
    const sessionId = String(req.query.session_id || '').trim();
    if (!sessionId || !sessionId.startsWith('cs_')) {
      return res.status(400).json({ error: 'Missing or invalid session_id' });
    }

    // Fast path: webhook already generated a token for this session.
    const existing = stripeSessions.get(sessionId);
    if (existing) {
      const entry = tokenStore.get(existing.token);
      if (entry) {
        const baseUrl = getBaseUrl();
        return res.status(200).json({
          success: true,
          downloadUrl: `${baseUrl}/d/${existing.token}`,
          expiresAt: existing.expiresAt.toISOString(),
          reused: true,
        });
      }
    }

    // Fallback: fetch the session directly from Stripe and generate a new token/PDF.
    const secretKey = process.env.STRIPE_SECRET_KEY;
    if (!secretKey) {
      return res.status(500).json({ error: 'STRIPE_SECRET_KEY is not configured' });
    }

    const stripe = new Stripe(secretKey);
    const session = await stripe.checkout.sessions.retrieve(sessionId);

    if (!isPaidSession(session)) {
      return res.status(402).json({
        error: 'Checkout Session is not paid (or not complete) yet',
        payment_status: session && session.payment_status,
        status: session && session.status,
      });
    }

    const buyer = stripeLib.buyerFromCheckoutSession(session);
    if (!buyer) {
      return res.status(400).json({ error: 'Unable to extract buyer email from Stripe session' });
    }

    const resolvedMaster = getResolvedMasterPdf();
    ensureTempDir();

    const token = crypto.randomBytes(32).toString('hex');
    const pdfPath = path.resolve(TEMP_DIR, `${token}.pdf`);
    await watermark.createWatermarkedPdf(resolvedMaster, pdfPath, buyer);

    const baseUrl = getBaseUrl();
    const { downloadUrl, expiresAt } = onetime.createOneTimeLink(token, pdfPath, baseUrl);

    stripeSessions.set(sessionId, token, expiresAt.getTime());

    res.status(200).json({
      success: true,
      downloadUrl,
      expiresAt: expiresAt.toISOString(),
      reused: false,
    });
  } catch (err) {
    console.error('Stripe fulfill error:', err);
    res.status(500).json({ error: 'Failed to fulfill purchase' });
  }
});

module.exports = router;

